### PR TITLE
fix(extension): #107: allow http for localhost

### LINKED ISSUE #107: Accept localhost connections without https
External teams are running into issues in local dev connecting to Prax because it has a strict https-only requirement. By default localhost is generally accessed through http. Changing web build tooling to point to https locally is a bit clunky. 

**Proposal:** allow Prax to make connections in a dev environment to http://localhost

This will circumvent the ongoing issue of dev teams reaching out to us because of mysterious connection issues.

### PR DESCRIPTION
**Pull request by VanishMax**
Closes #107 

1. Changes to the manifest to inject content scripts into http://localhost
2. Changes to the `assertValidSender` function to allow http://localhost

### CODE REVIEW

File: apps/extension/src/senders/validate.ts [hunk 1]
```diff
@@ -13,6 +13,10 @@ type ValidSender = chrome.runtime.MessageSender & {
   url: `${ValidProtocol}//${string}/${string}`;
 };
 
+const isException = (url: URL): boolean => {
+  return url.protocol === 'http:' && url.hostname === 'localhost';
+};
+
```
Comment (turbocrime) [inline apps/extension/src/senders/validate.ts:19]:
```suggestion
const isHttpLocalhost = (url: URL): boolean => 
  url.protocol === 'http:' && url.hostname === 'localhost';

```

File: apps/extension/src/senders/validate.ts [hunk 2]
```diff
@@ -34,7 +38,8 @@ export const assertValidSender = (sender?: chrome.runtime.MessageSender) => {
   if (parsedOrigin.origin !== sender.origin) {
     throw new Error('Sender origin is invalid');
   }
-  if (!(parsedOrigin.protocol in ValidProtocol)) {
+
+  if (!(parsedOrigin.protocol in ValidProtocol || isException(parsedOrigin))) {
```
Comment (turbocrime) [inline apps/extension/src/senders/validate.ts:42]:
```suggestion
  if (!(parsedOrigin.protocol in ValidProtocol || (globalThis.__DEV__ && isHttpLocalhost(parsedOrigin)))) {
```

**Review by turbocrime — APPROVED** [review]

File: apps/extension/public/manifest.json
Comment (turbocrime) [inline apps/extension/public/manifest.json:1]: i'd like to condition the manifest inclusion of `localhost` but that would require some additional build config

File: apps/extension/src/senders/validate.ts [hunk 3]
```diff
@@ -13,6 +13,10 @@ type ValidSender = chrome.runtime.MessageSender & {
   url: `${ValidProtocol}//${string}/${string}`;
```
Comment (turbocrime) [inline apps/extension/src/senders/validate.ts:13]: the origin/url type are incorrect now that validprotocol may conditionally be http at any moment. probably just set these to 'string'

Comment (turbocrime) [inline apps/extension/src/senders/validate.ts:13]: the origin/url type are incorrect now that validprotocol may conditionally be http at any moment. probably just set these to 'string'

**Review by turbocrime — CHANGES_REQUESTED** [review]
the ValidSender type needs correction but other than that, this would work

**Comment by turbocrime** [comment]
deps also need to support this https://github.com/penumbra-zone/web/blob/9da630e851cd7303372b3e1aac63d398305bba62/packages/transport-chrome/src/session-manager.ts#L99-L105

File: apps/extension/public/manifest.json
Comment (VanishMax) [reply apps/extension/public/manifest.json:1]: what do you mean by this?

File: apps/extension/src/senders/validate.ts (hunk 3 above)
Comment (VanishMax) [reply apps/extension/src/senders/validate.ts]: changed to `string`

**Comment by VanishMax** [comment]
@turbocrime pinging for your re-review
